### ISSUE TITLE
DFD Comments Sept 24

### ISSUE THREAD

**Issue by germonprez** [afmatar/ISQA3420#9]
Here are a few comments: 

In the Manager section: 

<img width="567" alt="screen shot 2016-09-24 at 6 57 54 am" src="https://cloud.githubusercontent.com/assets/656208/18808321/52c2c604-8224-11e6-9fcb-194e4804fbfd.png">

Data Request and Project Information Request should be named the same thing. Something like All Software Package and License Information Request. 

Same with Granular Data and Summarized Information. Are these the same thing? if they are, they should have the same name. And perhaps a more descriptive one at that. 

MG

**Comment by afmatar** [comment]
please find attache DFD i made some change

**Comment by germonprez** [comment]
Ok, good to see that they are same name. 

Now granular data --should be named--> Request for all Software Package License and Vulnerability Information. You have to be descriptive in your DFD. Something like Granular Data does not tell me very much. You should also provide a more descriptive name for Data Request. 

Don't forget to include the NIST vulnerability stuff from last week too. 

Matt

**Comment by afmatar** [comment]
i made some change In DFD i hope i did right please feel attached 
Thank you
